spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification-service
              uri: http://localhost:8082
              predicates:
                - Host=localhost:8082
              filters:
                - JwtSubToMemberIdHeader
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Host=localhost:8081
              filters:
                - JwtSubToMemberIdHeader
            - id: task-service
              uri: http://localhost:8080
              predicates:
                - Host=localhost:8080
              filters:
                - JwtSubToMemberIdHeader
          metrics:
            enabled: true
management:
  server:
    port: 9096
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

server:
  port: 8060

path:
  key:
    jwt:
      public: ${HOME}/pinit/keys/jwt-public-key.pem