spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification-service
              uri: http://localhost:8082
              predicates:
                - Host=http://localhost:8082
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Host=localhost:8081
            - id: task-service
              uri: http://localhost:8080
              predicates:
                - Host=localhost:8080

server:
  port: 8060